### ISSUE TITLE
direct pipe to improve performance

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/peer-crdt-ipfs#4]
Given that the bottleneck today is Bitswap, wouldn't an alternative, but temporary, solution be just opening a libp2p protocol (`.dialProtocol(/peer-crdt/1.0.0`) that sends the updates all together just like y.js does? 

//cc @pgte @fritzy

**Comment by pgte** [comment]
Y.js works by doing a handshake, where each side knows what's each others' latest, so that they can send only updates to each other.
Even so, I think we should create this as an alternative to the native DAG sync.
This would require a vector clock per operation (easily achievable).

**Comment by pgte** [comment]
Proposal for fixing this and add some scalability features: #5.
Comments are welcome.
